import { Deal, Member, Event, PortfolioEntry } from './types'

export const MEMBERS: Member[] = [
  {
    id: 'm1',
    name: 'Yash Varma',
    role: 'investor',
    background: 'Empress Capital, Sydney',
    thesisTags: ['FinTech', 'B2B SaaS'],
    chequeMin: 25000,
    chequeMax: 100000,
    geo: 'Sydney',
    availableThisMonth: true,
    engagementScore: 92,
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200',
  },
  {
    id: 'm2',
    name: 'Sarah Chen',
    role: 'investor',
    background: 'Ex-Canva, Melbourne',
    thesisTags: ['B2B SaaS', 'AI/ML', 'DesignTech'],
    chequeMin: 50000,
    chequeMax: 200000,
    geo: 'Melbourne',
    availableThisMonth: true,
    engagementScore: 87,
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200',
  },
  {
    id: 'm3',
    name: 'Marcus Webb',
    role: 'investor',
    background: 'Ex-Afterpay CFO, Sydney',
    thesisTags: ['FinTech', 'ClimaTech'],
    chequeMin: 100000,
    chequeMax: 500000,
    geo: 'Sydney',
    availableThisMonth: false,
    engagementScore: 74,
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200',
  },
  {
    id: 'm4',
    name: 'Priya Nair',
    role: 'investor',
    background: 'Healthcare operator, Brisbane',
    thesisTags: ['HealthTech', 'MedTech'],
    chequeMin: 25000,
    chequeMax: 75000,
    geo: 'Brisbane',
    availableThisMonth: true,
    engagementScore: 81,
    avatar: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=200',
  },
  {
    id: 'm5',
    name: 'James Thornton',
    role: 'investor',
    background: 'Family office, Melbourne',
    thesisTags: ['AgTech', 'Logistics', 'ClimaTech'],
    chequeMin: 50000,
    chequeMax: 250000,
    geo: 'Melbourne',
    availableThisMonth: true,
    engagementScore: 68,
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200',
  },
]

export const DEALS: Deal[] = [
  {
    id: 'd1',
    name: 'Luma Health',
    sector: 'HealthTech',
    stage: 'Pre-seed',
    ask: '$500K',
    oneLiner: 'AI-powered triage for rural GPs',
    description:
      'Luma Health uses machine learning to assist rural general practitioners with patient triage, reducing wait times and improving outcomes in underserved regions across Australia.',
    status: 'Screening',
    heroImage: 'https://images.unsplash.com/photo-1504608524841-42fe6f032b4b?w=800&h=400&fit=crop',
    founderName: 'Dr. Anika Patel',
    founderEmail: 'anika@lumahealth.com.au',
    traction: 'Pilot with 3 rural clinics in NSW. 200+ patients triaged. 40% reduction in wait times.',
    createdAt: '2026-01-15',
    tags: ['HealthTech', 'AI/ML', 'Rural'],
    interests: [
      { investorId: 'm4', signal: 'interested' },
      { investorId: 'm2', signal: 'watching' },
      { investorId: 'm1', signal: 'interested' },
    ],
    softCircles: [
      { investorId: 'm4', amount: 50000 },
      { investorId: 'm1', amount: 25000 },
    ],
    questions: [
      {
        id: 'q1',
        dealId: 'd1',
        text: 'What is the regulatory pathway for AI-assisted triage in Australia?',
        authorId: 'm3',
        upvotes: 4,
        pinned: true,
        createdAt: '2026-01-20',
      },
      {
        id: 'q2',
        dealId: 'd1',
        text: 'How does the model handle edge cases with elderly patients?',
        authorId: 'm2',
        upvotes: 2,
        pinned: false,
        createdAt: '2026-01-22',
      },
    ],
  },
  {
    id: 'd2',
    name: 'Fieldstack',
    sector: 'AgTech',
    stage: 'Seed',
    ask: '$1.2M',
    oneLiner: 'IoT soil monitoring for broadacre farms',
    description:
      'Fieldstack deploys low-cost IoT sensors across broadacre farms to provide real-time soil health data, enabling precision agriculture and reducing water waste by up to 30%.',
    status: 'Diligence',
    heroImage: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=400&fit=crop',
    founderName: 'Tom Reeves',
    founderEmail: 'tom@fieldstack.io',
    traction: '12 farms onboarded across QLD and NSW. $180K ARR. 95% retention rate.',
    createdAt: '2025-11-20',
    tags: ['AgTech', 'IoT', 'ClimaTech'],
    interests: [
      { investorId: 'm5', signal: 'interested' },
      { investorId: 'm3', signal: 'interested' },
      { investorId: 'm1', signal: 'watching' },
    ],
    softCircles: [
      { investorId: 'm5', amount: 100000 },
      { investorId: 'm3', amount: 200000 },
    ],
    questions: [
      {
        id: 'q3',
        dealId: 'd2',
        text: 'What is the unit economics per farm? How does cost scale with acreage?',
        authorId: 'm5',
        upvotes: 3,
        pinned: false,
        createdAt: '2025-12-01',
      },
    ],
  },
  {
    id: 'd3',
    name: 'Voxa AI',
    sector: 'B2B SaaS',
    stage: 'Seed',
    ask: '$800K',
    oneLiner: 'Voice analytics for call centre compliance',
    description:
      'Voxa AI analyses call centre conversations in real-time to flag compliance risks, detect sentiment shifts, and automate quality assurance — saving enterprise clients millions in regulatory fines.',
    status: 'New',
    heroImage: 'https://images.unsplash.com/photo-1534088568595-a066f410bcda?w=800&h=400&fit=crop',
    founderName: 'Liam Santos',
    founderEmail: 'liam@voxa.ai',
    traction: '2 enterprise pilots (Big 4 bank, telco). $90K in pilot revenue.',
    createdAt: '2026-02-01',
    tags: ['B2B SaaS', 'AI/ML', 'FinTech'],
    interests: [
      { investorId: 'm2', signal: 'interested' },
      { investorId: 'm1', signal: 'interested' },
    ],
    softCircles: [{ investorId: 'm2', amount: 75000 }],
    questions: [],
  },
  {
    id: 'd4',
    name: 'CarbonLedger',
    sector: 'ClimaTech',
    stage: 'Pre-seed',
    ask: '$400K',
    oneLiner: 'Real-time Scope 3 carbon tracking',
    description:
      'CarbonLedger automates Scope 3 emissions tracking for mid-market companies, integrating directly with ERP and procurement systems to provide auditable, real-time carbon data.',
    status: 'Intro Requested',
    heroImage: 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=800&h=400&fit=crop',
    founderName: 'Zara Okonkwo',
    founderEmail: 'zara@carbonledger.co',
    traction: 'Pre-revenue. 3 LOIs from ASX 200 companies. Pilot underway with anchor customer.',
    createdAt: '2026-01-28',
    tags: ['ClimaTech', 'FinTech', 'ESG'],
    interests: [
      { investorId: 'm3', signal: 'interested' },
      { investorId: 'm5', signal: 'interested' },
      { investorId: 'm2', signal: 'watching' },
    ],
    softCircles: [
      { investorId: 'm3', amount: 100000 },
      { investorId: 'm5', amount: 75000 },
    ],
    questions: [
      {
        id: 'q4',
        dealId: 'd4',
        text: 'How does this compare to existing carbon accounting platforms like Watershed?',
        authorId: 'anon',
        upvotes: 5,
        pinned: true,
        createdAt: '2026-02-05',
      },
    ],
  },
  {
    id: 'd5',
    name: 'Skipper',
    sector: 'Logistics',
    stage: 'Seed',
    ask: '$1M',
    oneLiner: 'Last-mile routing for regional Australia',
    description:
      'Skipper optimises last-mile delivery routes for regional and rural Australia, reducing delivery costs by 25% and cutting carbon emissions through intelligent route planning.',
    status: 'Investing',
    heroImage: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&h=400&fit=crop',
    founderName: 'Ben Hargraves',
    founderEmail: 'ben@skipper.com.au',
    traction: '45 logistics partners. $320K MRR. Growing 15% month-on-month.',
    createdAt: '2025-10-10',
    tags: ['Logistics', 'AI/ML', 'RegionalTech'],
    interests: [
      { investorId: 'm5', signal: 'interested' },
      { investorId: 'm1', signal: 'interested' },
      { investorId: 'm3', signal: 'watching' },
      { investorId: 'm2', signal: 'pass' },
    ],
    softCircles: [
      { investorId: 'm5', amount: 150000 },
      { investorId: 'm1', amount: 50000 },
    ],
    questions: [
      {
        id: 'q5',
        dealId: 'd5',
        text: 'What happens when Australia Post rolls out a similar optimisation tool?',
        authorId: 'm1',
        upvotes: 6,
        pinned: false,
        createdAt: '2025-10-15',
      },
    ],
  },
]

export const EVENTS: Event[] = [
  {
    id: 'e1',
    title: 'HealthTech Deep Dive',
    date: '2026-03-18',
    location: 'Sydney',
    sector: 'HealthTech',
    capacity: 30,
    rsvpCount: 18,
    founders: ['Dr. Anika Patel (Luma Health)', 'Chris Nguyen (MedFlow)', 'Sophie Walsh (CareLink)'],
    heroImage: 'https://images.unsplash.com/photo-1517483000871-1dbf64a6e1c6?w=800&h=400&fit=crop',
    rsvpd: ['m1', 'm2', 'm4'],
  },
  {
    id: 'e2',
    title: 'Climate & Cleantech',
    date: '2026-05-22',
    location: 'Melbourne',
    sector: 'ClimaTech',
    capacity: 25,
    rsvpCount: 12,
    founders: ['Zara Okonkwo (CarbonLedger)', 'Mike Tan (SolarGrid)', 'Ella Price (GreenByte)'],
    heroImage: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&h=400&fit=crop',
    rsvpd: ['m3', 'm5'],
  },
  {
    id: 'e3',
    title: 'AI & Automation',
    date: '2026-07-17',
    location: 'Sydney',
    sector: 'AI/ML',
    capacity: 30,
    rsvpCount: 8,
    founders: ['Liam Santos (Voxa AI)', 'Nina Park (AutoPilot)', 'Raj Mehta (SynthLab)'],
    heroImage: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&h=400&fit=crop',
    rsvpd: ['m1', 'm2'],
  },
]

export const PORTFOLIO_ENTRIES: PortfolioEntry[] = [
  { memberId: 'm1', dealId: 'd5', amount: 50000, date: '2025-11-01', status: 'active' },
  { memberId: 'm5', dealId: 'd5', amount: 150000, date: '2025-11-01', status: 'active' },
  { memberId: 'm3', dealId: 'd2', amount: 200000, date: '2025-12-15', status: 'active' },
  { memberId: 'm5', dealId: 'd2', amount: 100000, date: '2025-12-15', status: 'active' },
  { memberId: 'm4', dealId: 'd1', amount: 50000, date: '2026-01-20', status: 'active' },
  { memberId: 'm1', dealId: 'd1', amount: 25000, date: '2026-01-20', status: 'active' },
  { memberId: 'm2', dealId: 'd3', amount: 75000, date: '2026-02-10', status: 'active' },
]
